name: Generate Documentation

on: [ workflow_dispatch, repository_dispatch ]

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Download Documentation Code
        uses: actions/checkout@v2
        with:
          ref: docs
          repository: Ayfri/PIXI-Utils

      - name: Download Library
        uses: actions/checkout@v2
        with:
          ref: master
          repository: Ayfri/PIXI-Utils
          path: 'source'

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm i

      - name: Generate Documentation
        run: npm run generate

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add docs -f
          git commit -m "Generated documentation."
          git push origin docs
